stu_app/urls.py
from django.urls import path, include
from . import views
from .import AdminViews, StaffViews, StudentViews


urlpatterns = [
    path('', views.loginPage, name="login"),
    path('Login/', views.Login, name="Login"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', AdminViews.admin_home, name="admin_home"),
    path('add_staff/', AdminViews.add_staff, name="add_staff"),
    path('add_staff_save/', AdminViews.add_staff_save, name="add_staff_save"),
    path('manage_staff/', AdminViews.manage_staff, name="manage_staff"),
    path('edit_staff/<staff_id>/', AdminViews.edit_staff, name="edit_staff"),
    path('edit_staff_save/', AdminViews.edit_staff_save, name="edit_staff_save"),
    path('delete_staff/<staff_id>/', AdminViews.delete_staff, name="delete_staff"),
    path('add_class_gr/', AdminViews.add_class_gr, name="add_class_gr"),
    path('add_classgr_save/', AdminViews.add_classgr_save, name="add_classgr_save"),
    path('manage_classgr/', AdminViews.manage_classgr, name="manage_classgr"),
    path('edit_classgr/<class_id>/', AdminViews.edit_classgr, name="edit_classgr"),
    path('edit_classgr_save/', AdminViews.edit_classgr_save, name="edit_classgr_save"),
    path('delete_classgr/<class_id>/', AdminViews.delete_classgr, name="delete_classgr"),
    path('add_student/', AdminViews.add_student, name="add_student"),
    path('add_student_save/', AdminViews.add_student_save, name="add_student_save"),
    path('edit_student/<student_id>', AdminViews.edit_student, name="edit_student"),
    path('edit_student_save/', AdminViews.edit_student_save, name="edit_student_save"),
    path('manage_student/', AdminViews.manage_student, name="manage_student"),
    path('delete_student/<student_id>/', AdminViews.delete_student, name="delete_student"),
    path('add_subject/', AdminViews.add_subject, name="add_subject"),
    path('add_subject_save/', AdminViews.add_subject_save, name="add_subject_save"),
    path('manage_subject/', AdminViews.manage_subject, name="manage_subject"),
    path('edit_subject/<subject_id>/', AdminViews.edit_subject, name="edit_subject"),
    path('edit_subject_save/', AdminViews.edit_subject_save, name="edit_subject_save"),
    path('delete_subject/<subject_id>/', AdminViews.delete_subject, name="delete_subject"),
    path('check_email_exist/', AdminViews.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', AdminViews.check_username_exist, name="check_username_exist"),
    path('manage_schyear/', AdminViews.manage_schyear, name="manage_schyear"),
    path('add_schyear/', AdminViews.add_schyear, name="add_schyear"),
    path('add_schyear_save/', AdminViews.add_schyear_save, name="add_schyear_save"),
    path('edit_schyear/<schyear_id>', AdminViews.edit_schyear, name="edit_schyear"),
    path('edit_schyear_save/', AdminViews.edit_schyear_save, name="edit_schyear_save"),
    path('delete_schyear/<schyear_id>/', AdminViews.delete_schyear, name="delete_schyear"),

    path('staff_home/', StaffViews.staff_home, name="staff_home"),
    path('staff_take_attendance/', StaffViews.staff_take_attendance, name="staff_take_attendance"),
    path('get_students/', StaffViews.get_students, name="get_students"),
    path('save_attendance_data/', StaffViews.save_attendance_data, name="save_attendance_data"),
    path('staff_edit_attendance/', StaffViews.staff_edit_attendance, name="staff_edit_attendance"),
    path('get_attendance_dates/', StaffViews.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_student/', StaffViews.get_attendance_student, name="get_attendance_student"),
    path('edit_attendance_data/', StaffViews.edit_attendance_data, name="edit_attendance_data"),
    path('staff_add_grade/', StaffViews.staff_add_grade, name="staff_add_grade"),
    path('staff_add_grade_save/', StaffViews.staff_add_grade_save, name="staff_add_grade_save"),

    path('student_home/', StudentViews.student_home, name="student_home"),
    path('student_view_attendance/', StudentViews.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post/', StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('student_view_grade/', StudentViews.student_view_grade, name="student_view_grade"),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from system import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stu_app.urls')),
]

stu_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver



class SchoolYear(models.Model):
    id = models.AutoField(primary_key=True)
    school_start = models.DateField()
    schooly_end = models.DateField()
    objects = models.Manager()



# Overriding the Default Django Auth User and adding One More Field (user_type)
class CustomUser(AbstractUser):
    user_type_data = ((1, "Admin"), (2, "Staff"), (3, "Student"))
    user_type = models.CharField(default=1, choices=user_type_data, max_length=10)



class Admin(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
   
    objects = models.Manager()


class Staffs(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete = models.CASCADE)

    objects = models.Manager()



class ClassGroup(models.Model):
    id = models.AutoField(primary_key=True)
    class_name = models.CharField(max_length=255)
   
    objects = models.Manager()



class Subjects(models.Model):
    id =models.AutoField(primary_key=True)
    subject_name = models.CharField(max_length=255)
    class_id = models.ForeignKey(ClassGroup, on_delete=models.CASCADE, default=1) #need to give defauult classgrid
    staff_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
 
    objects = models.Manager()



class Students(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
 
    class_id = models.ForeignKey(ClassGroup, on_delete=models.DO_NOTHING, default=1)
    school_year_id = models.ForeignKey(SchoolYear, on_delete=models.CASCADE)
   
    objects = models.Manager()


class Attendance(models.Model):
    # Subject Attendance
    id = models.AutoField(primary_key=True)
    subject_id = models.ForeignKey(Subjects, on_delete=models.DO_NOTHING)
    attendance_date = models.DateField()
    school_year_id = models.ForeignKey(SchoolYear, on_delete=models.CASCADE)
   
    objects = models.Manager()


class AttendanceReport(models.Model):
    # Individual Student Attendance
    id = models.AutoField(primary_key=True)
    student_id = models.ForeignKey(Students, on_delete=models.DO_NOTHING)
    attendance_id = models.ForeignKey(Attendance, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    objects = models.Manager()


class StudentGrade(models.Model):
    id = models.AutoField(primary_key=True)
    student_id = models.ForeignKey(Students, on_delete=models.CASCADE)
    subject_id = models.ForeignKey(Subjects, on_delete=models.CASCADE)
    subject_exam_points = models.FloatField(default=0)
   
    objects = models.Manager()


#Creating Django Signals

# It's like trigger in database. It will run only when Data is Added in CustomUser model

@receiver(post_save, sender=CustomUser)
# Now Creating a Function which will automatically insert data in HOD, Staff or Student
def create_user_profile(sender, instance, created, **kwargs):
    # if Created is true (Means Data Inserted)
    if created:
        # Check the user_type and insert the data in respective tables
        if instance.user_type == 1:
            admin.objects.create(admin=instance)
        if instance.user_type == 2:
            Staffs.objects.create(admin=instance)
        if instance.user_type == 3:
            Students.objects.create(admin=instance, class_id=ClassGroup.objects.get(id=1), school_year_id=SchoolYear.objects.get(id=1))
    

@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.admin.save()
    if instance.user_type == 2:
        instance.staffs.save()
    if instance.user_type == 3:
        instance.students.save()
    

stu_app/forms.py
from django import forms 
from django.forms import Form
from stu_app.models import ClassGroup, SchoolYear


class DateInput(forms.DateInput):
    input_type = "date"


class AddStudent(forms.Form):
    email = forms.EmailField(label="Email", max_length=50, widget=forms.EmailInput(attrs={"class":"form-control"}))
    password = forms.CharField(label="Password", max_length=50, widget=forms.PasswordInput(attrs={"class":"form-control"}))
    first_name = forms.CharField(label="First Name", max_length=50, widget=forms.TextInput(attrs={"class":"form-control"}))
    last_name = forms.CharField(label="Last Name", max_length=50, widget=forms.TextInput(attrs={"class":"form-control"}))
    username = forms.CharField(label="Username", max_length=50, widget=forms.TextInput(attrs={"class":"form-control"}))

    #For Displaying Courses
    try:
        classes = ClassGroup.objects.all()
        class_list = []
        for classgr in classes:
            single_class = (classgr.id, classgr.class_name)
            class_list.append(single_class)
    except:
        class_list = []
    
    try:
        school_years = SchoolYear.objects.all()
        school_year_list = []
        for school_year in school_years:
            single_school_year = (school_year.id, str(school_year.school_start)+" to "+str(school_year.schooly_end))
            school_year_list.append(single_school_year)
            
    except:
        school_year_list = []
    
   
    class_id = forms.ChoiceField(label="Class", choices=class_list, widget=forms.Select(attrs={"class":"form-control"}))
    school_year_id = forms.ChoiceField(label="School Year", choices=school_year_list, widget=forms.Select(attrs={"class":"form-control"}))



class EditStudent(forms.Form):
    email = forms.EmailField(label="Email", max_length=50, widget=forms.EmailInput(attrs={"class":"form-control"}))
    first_name = forms.CharField(label="First Name", max_length=50, widget=forms.TextInput(attrs={"class":"form-control"}))
    last_name = forms.CharField(label="Last Name", max_length=50, widget=forms.TextInput(attrs={"class":"form-control"}))
    username = forms.CharField(label="Username", max_length=50, widget=forms.TextInput(attrs={"class":"form-control"}))

    #For Displaying Courses
    try:
        classes = ClassGroup.objects.all()
        class_list = []
        for classgr in classes:
            single_class = (classgr.id, classgr.class_name)
            class_list.append(single_class)
    except:
        class_list = []


    try:
        school_years = SchoolYear.objects.all()
        school_year_list = []
        for school_year in school_years:
            single_school_year = (school_year.id, str(school_year.school_start)+" to "+str(school_year.schooly_end))
            school_year_list.append(single_school_year)
            
    except:
        school_year_list = []

   
    
    class_id = forms.ChoiceField(label="Class", choices=class_list, widget=forms.Select(attrs={"class":"form-control"}))
    school_year_id = forms.ChoiceField(label="School Year", choices=school_year_list, widget=forms.Select(attrs={"class":"form-control"}))
  

stu_app/views.py
# from channels.auth import login, logout
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect

from stu_app.auth import auth


def home(request):
    return render(request, 'base.html')


def loginPage(request):
    return render(request, 'login.html')

def Login(request):
    if request.method != "POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        user = auth.authenticate(request, username=request.POST.get('email'), password=request.POST.get('password'))
        if user != None:
            login(request, user)
            user_type = user.user_type
            if user_type == '1':
                return redirect('admin_home')
                
            elif user_type == '2':
                return redirect('staff_home')
                
            elif user_type == '3':
                return redirect('student_home')
            else:
                return redirect('login')
        else:
            return redirect('login')



def get_user_details(request):
    if request.user != None:
        return HttpResponse("User: "+request.user.email+" User Type: "+request.user.user_type)
    else:
        return HttpResponse("Please Login First")



def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')

stu_app/templates/admin_t/add_class_gr.html
{% extends 'admin_t/base.html' %}

{% block page_title %}
    Add Class Group
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <!-- form start -->
                    <form role="form" method="POST" action="{% url 'add_classgr_save' %}">
                        {% csrf_token %}    

                        <div class="card-body">
                            <div class="form-group">
                                <label>Class Name </label>
                                <input type="text" class="form-control" name="classgr" placeholder="Enter Class Group">
                            </div>

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-secondary">Add Class Group</button>
                        </div>
                    </form>
                    </div>
                    <!-- /.card -->
               
                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

stu_app/templates/admin_t/add_schyear.html
{% extends 'admin_t/base.html' %}

{% block page_title %}
    Add School Year
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    
                    <!-- form start -->
                    <form role="form" method="POST" action="{% url 'add_schyear_save' %}">
                        {% csrf_token %}

                        <div class="card-body">
                            <div class="form-group">
                                <label>Start </label>
                                <input type="date" class="form-control" name="school_start">
                            </div>

                            <div class="form-group">
                                <label>End </label>
                                <input type="date" class="form-control" name="schooly_end">
                            </div>

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-secondary">Save</button>
                        </div>
                    </form>
                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

stu_app/templates/admin_t/add_student.html
{% extends 'admin_t/base.html' %}


{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-secondary">
                  
                    {% url 'add_student_save' as action_path %}
                    {% include 'admin_t/student_form.html' with form=form action_path=action_path button_text="Add Student" %}

                    </div>
                  

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

  {% block custom_js %}

    <script>
        //     Checking if email and username already exists or not using Ajax 
        $(document).ready(function(){
            $("#id_email").keyup(function(){
                var email = $(this).val();

                if(email!=""){
                    $.ajax({
                        url : "{% url 'check_email_exist' %}",
                        type : 'POST',
                        data : {email:email}
                    })
                    .done(function(response){

                        if(response == "True"){
                            $(".email_error").remove();
                            $("<span class='email_error' style='color: red; padding: 5px; font-weight: bold;'> Email Not Available. </span>").insertAfter("#id_email")
                        }
                        else{
                            $(".email_error").remove();
                            $("<span class='email_error' style='color: green; padding: 5px; font-weight: bold;'> Email Available. </span>").insertAfter("#id_email")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".email_error").remove();
                }
                
            })

            $("#id_username").keyup(function(){
                var username = $(this).val();
                
                if(username!=""){
                    $.ajax({
                        url : "{% url 'check_username_exist' %}",
                        type : 'POST',
                        data : {username:username}
                    })
                    .done(function(response){

                        if(response == "True"){
                            $(".username_error").remove();
                            $("<span class='username_error' style='color: red; padding: 5px; font-weight: bold;'> Username Not Available. </span>").insertAfter("#id_username")
                        }
                        else{
                            $(".username_error").remove();
                            $("<span class='username_error' style='color: green; padding: 5px; font-weight: bold;'> Username Available. </span>").insertAfter("#id_username")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".username_error").remove();
                }
                
            })
        })
    </script>

  {% endblock custom_js %}

stu_app/templates/admin_t/add_subject.html
{% extends 'admin_t/base.html' %}

{% block page_title %}
    Add Subject
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                  
                    <form role="form" method="POST" action="{% url 'add_subject_save' %}">
                        {% csrf_token %}


                        <div class="card-body">
                            <div class="form-group">
                                <label>Subject Name </label>
                                <input type="text" class="form-control" name="subject" placeholder="Enter Subject">
                            </div>

                            <div class="form-group">
                                <label>Class </label>
                                <select class="form-control" name="classgr">
                                    {% for classgr in classgrs %}
                                        <option value="{{ classgr.id }}">{{ classgr.class_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Staff </label>
                                <select class="form-control" name="staff">
                                    {% for staff in staffs %}
                                        <option value="{{ staff.id }}">{{ staff.first_name }} {{ staff.last_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-secondary">Add</button>
                        </div>
                    </form>
                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

stu_app/templates/admin_t/add_teach.html
{% extends 'admin_t/base.html' %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                
                    <form role="form" method="POST" action="{% url 'add_staff_save' %}">
                        {% csrf_token %}

                        <div class="card-body">
                            <div class="form-group">
                                <label>Email address</label>
                                <input type="email" class="form-control" name="email" placeholder="Enter email" id="id_email">
                            </div>

                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" class="form-control" name="username" placeholder="Username" id="id_username">
                            </div>

                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control" name="password" placeholder="Password">
                            </div>

                            <div class="form-group">
                                <label>First Name</label>
                                <input type="text" class="form-control" name="first_name" placeholder="First Name">
                            </div>

                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control" name="last_name" placeholder="Last Name">
                            </div>

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-secondary">Add Staff</button>
                        </div>
                    </form>
                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

    {% block custom_js %}

    <script>
        $(document).ready(function(){
            $("#id_email").keyup(function(){
                var email = $(this).val();

                if(email!=""){
                    $.ajax({
                        url : "{% url 'check_email_exist' %}",
                        type : 'POST',
                        data : {email:email}
                    })
                    .done(function(response){

                        if(response == "True"){
                            $(".email_error").remove();
                            $("<span class='email_error' style='color: red; padding: 5px; font-weight: bold;'> Email Not Available. </span>").insertAfter("#id_email")
                        }
                        else{
                            $(".email_error").remove();
                            $("<span class='email_error' style='color: green; padding: 5px; font-weight: bold;'> Email Available. </span>").insertAfter("#id_email")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".email_error").remove();
                }
                
            })

            $("#id_username").keyup(function(){
                var username = $(this).val();
                
                if(username!=""){
                    $.ajax({
                        url : "{% url 'check_username_exist' %}",
                        type : 'POST',
                        data : {username:username}
                    })
                    .done(function(response){

                        if(response == "True"){
                            $(".username_error").remove();
                            $("<span class='username_error' style='color: red; padding: 5px; font-weight: bold;'> Username Not Available. </span>").insertAfter("#id_username")
                        }
                        else{
                            $(".username_error").remove();
                            $("<span class='username_error' style='color: green; padding: 5px; font-weight: bold;'> Username Available. </span>").insertAfter("#id_username")
                        }
                    })

                    .fail(function(){
                        console.log("Failed");
                    })
                }
                else{
                    $(".username_error").remove();
                }
                
            })
        })
    </script>

  {% endblock custom_js %}

stu_app/templates/admin_t/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="{% static 'tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <link rel="stylesheet" href="{% static 'icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'jqvmap/jqvmap.min.css' %}">
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.css'  %}">
  <link rel="stylesheet" href="{% static 'overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <link rel="stylesheet" href="{% static 'daterangepicker/daterangepicker.css' %}">
  <link rel="stylesheet" href="{% static 'summernote/summernote-bs4.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


</head>

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">

  <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">      
          <a href="{% url 'logout_user' %}" >
            <i class="fas fa-power-off mr-2"></i> Logout
          </a>
      
    </ul>

    </nav>

    {% include 'admin_t/sidebar.html' with user=user id=id %}

    <div class="content-wrapper">

      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">
                {% block page_title %}
                {% endblock page_title %}
              </h1>
            </div>
          
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
     
      {% block main_content %}
      {% endblock main_content %}

    </div>
 
  </div>
  
<script src="{% static 'jquery/jquery.min.js'  %}"></script>
<script src="{% static 'jquery-ui/jquery-ui.min.js'  %}"></script>
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js'  %}"></script>

<script src="{% static 'sparklines/sparkline.js'  %}"></script>
<script src="{% static 'jqvmap/jquery.vmap.min.js'  %}"></script>
<script src="{% static 'jqvmap/maps/jquery.vmap.usa.js'  %}"></script>
<script src="{% static 'jquery-knob/jquery.knob.min.js'  %}"></script>
<script src="{% static 'moment/moment.min.js'  %}"></script>
<script src="{% static 'daterangepicker/daterangepicker.js'  %}"></script>
<script src="{% static 'tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'  %}"></script>
<script src="{% static 'summernote/summernote-bs4.min.js'  %}"></script>
<script src="{% static 'overlayScrollbars/js/jquery.overlayScrollbars.min.js'  %}"></script>
<script src="{% static 'dist/js/adminlte.js'  %}"></script>
<script src="{% static 'dist/js/pages/dashboard.js'  %}"></script>
<script src="{% static 'dist/js/demo.js'  %}"></script>

{% block custom_js %}
{% endblock custom_js %}

</body>
</html>

stu_app/templates/admin_t/edit_class_gr.html
{% extends 'admin_t/base.html' %}

{% block page_title %}
    Edit Class Group 
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                   
                    <form role="form" method="POST" action="{% url 'edit_classgr_save' %}">
                        {% csrf_token %}

                        <div class="card-body">
                            <div class="form-group">
                                <label>Class Group Name </label>
                                <input type="text" class="form-control" name="class" value="{{ classgr.class_name }}">
                                <input type="hidden" name="class_id" value="{{ classgr.id }}" />
                            </div>

                        </div>

                        <div class="card-footer">
                        <button type="submit" class="btn btn-secondary">Save</button>
                        </div>
                    </form>
                    </div>

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}